export const LOADING_DATA = "LOADING_DATA";
export const UPDATE_DATA_NAME = "UPDATE_DATA_NAME";
export const UPDATE_MODEL_NAME = "UPDATE_MODEL_NAME";
export const UPDATE_INDIVIDUAL_SIM = "UPDATE_INDIVIDUAL_SIM";
export const UPDATE_INDIVIDUAL_RES_SIM = "UPDATE_INDIVIDUAL_RES_SIM";
export const UPDATE_CLUSTER_SLIDER_VALUE = "UPDATE_CLUSTER_SLIDER_VALUE";
export const UPDATE_SELECTED_CLUSTER = "UPDATE_SELECTED_CLUSTER";
export const UPDATE_SELECTED_ATTRIBUTES = "UPDATE_SELECTED_ATTRIBUTES";
export const UPDATE_HIGHLIGHTED_ATTRIBUTE = "UPDATE_HIGHLIGHTED_ATTRIBUTE";
export const UPDATE_TABLE_DATA = "UPDATE_TABLE_DATA";
export const UPDATE_LASSO_SELECTED = "UPDATE_LASSO_SELECTED";
export const UPDATE_BRUSH_CLUSTER_SELECTED = "UPDATE_BRUSH_CLUSTER_SELECTED";
export const UPDATE_PAIRWISE_COMMON_ATTRIBUTES =
    "UPDATE_PAIRWISE_COMMON_ATTRIBUTES";
